### ISSUE TITLE
Bug when there are multiple comments per statement

### ISSUE THREAD

**Issue by HenkPoley** [prettier/plugin-php#1150]
**Prettier 1.18.2**

**PHP Plugin 0.11.2**

```sh
# Options (if any):
```

**Input:**
Found in the wild at: https://github.com/tecnickcom/TCPDF/blob/master/include/barcodes/qrcode.php#L1322

```php
<?php

$a = 1
  * // A
  2
  * // B
  3;
```

**Output:**

```php
Comment "// B" was not printed. Please report this error!
```

**Expected behavior:**

**Comment by badams** [comment]
Also getting this some examples

```
//check if the offer applies to this site
        //state mismatch
        if (
            !$this->pricingQueryOfferResult->offer ||
            !$this->pricingQueryOfferResult->offer->offerGroup ||
            //!$this->pricingQuerySite->postcode ||
            ( // offer has a state but we don't
                $this->pricingQueryOfferResult->offer->offerGroup->state_id
                    && !$this->pricingQuerySite->postcode->state_id
            ) ||
            ( // if we have a state and the offer has a state and they don't match, reject
                $this->pricingQuerySite->postcode
                && $this->pricingQuerySite->postcode->state_id
                && $this->pricingQueryOfferResult->offer->offerGroup->state_id
                && $this->pricingQuerySite->postcode->state_id != $this->pricingQueryOfferResult->offer->offerGroup->state_id
            )
        ) {
            $this->hasResult = false;
            $this->removedReason = 'State Mismatch';
        }
```

```
[error] xx.php: Error: Comment "// offer has a state but we don't" was not printed. Please report this error!
[error]     at xx/node_modules/prettier/bin-prettier.js:13861:13
[error]     at Array.forEach (<anonymous>)
[error]     at ensureAllCommentsPrinted (xx/node_modules/prettier/bin-prettier.js:13859:15)
[error]     at coreFormat (xx/node_modules/prettier/bin-prettier.js:13908:3)
[error]     at format (xx/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/xx/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (xx/node_modules/prettier/bin-prettier.js:42758:15)
[error]     at format$1 (xx/node_modules/prettier/bin-prettier.js:44127:21)
[error]     at xx/node_modules/prettier/bin-prettier.js:44322:16
[error]     at xx/node_modules/prettier/bin-prettier.js:44262:14
```

**Comment by evilebottnawi** [comment]
We are working on this
