### ISSUE TITLE
Error: Invalid trailingCommaPHP value. Expected true or false, but received "php7.2"

### ISSUE THREAD

**Issue by mean-cj** [prettier/plugin-php#1378]
Hello today my vscode auto update extension 

My php code doesn't format after save

**Prettier 2.0.2**
**Prettier-vscode 4.0**
**PHP Plugin 0.14.0**

Found : 
Error: Invalid trailingCommaPHP value. Expected true or false, but received "php7.2"

**Output:**
["INFO" - 5:54:26 PM] Formatting file.php
["INFO" - 5:54:26 PM] Using ignore file (if present) at .prettierignore
["INFO" - 5:54:26 PM] Using bundled version of prettier.
["INFO" - 5:54:26 PM] File Info:
{
  "ignored": false,
  "inferredParser": "php"
}
["INFO" - 5:54:26 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:54:26 PM] Prettier Options:
{
  "filepath": "...file.php",
  "parser": "php",
  "semi": false,
  "arrowParens": "always",
  "singleQuote": true,
  "printWidth": 500,
  "tabWidth": 3,
  "html.format.wrapAttributes": "force-aligned",
  "trailingCommaPHP": "php7.2"
}
**["ERROR" - 5:54:26 PM] Error formatting document.
["ERROR" - 5:54:26 PM] Invalid trailingCommaPHP value. Expected true or false, but received "php7.2".**
Error: Invalid trailingCommaPHP value. Expected true or false, but received "php7.2".
	at Normalizer._applyNormalization (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:6098:59)
	at applyNormalization (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:6047:48)
	at Normalizer.normalize (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:6053:7)
	at normalizeOptions (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:8261:33)
	at Object.normalizeApiOptions (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:8389:10)
	at normalize$1 (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:11470:28)
	at formatWithCursor (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:15046:12)
	at esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:50695:12
	at Object.format (esbenp.prettier-vscode-4.0.0\node_modules\prettier\index.js:50715:12)
	at esbenp.prettier-vscode-4.0.0\dist\extension.js:1:328141
	at t.default.safeExecution (esbenp.prettier-vscode-4.0.0\dist\extension.js:1:328441)
	at t.default.<anonymous> (esbenp.prettier-vscode-4.0.0\dist\extension.js:1:328121)
	at Generator.next (<anonymous>)
	at s (esbenp.prettier-vscode-4.0.0\dist\extension.js:1:322312)
["INFO" - 5:54:26 PM] Formatting completed in 15.7048ms.

thank

**Comment by czosel** [comment]
Please see #1373.
