### ISSUE TITLE
Breaks if code contains type casting

### ISSUE THREAD

**Issue by duclet** [prettier/plugin-php#1438]
Updated to the most recent version of this plugin and prettier and noticed a bug such as the following:

```
TypeError: Cannot read property 'comments' of undefined
[error]     at printNode (/artemis-frontend/frontend/node_modules/@prettier/plugin-php/src/printer.js:2563:19)
[error]     at Object.genericPrint [as print] (/artemis-frontend/frontend/node_modules/@prettier/plugin-php/src/printer.js:93:32)
[error]     at callPluginPrintFunction (/artemis-frontend/frontend/node_modules/prettier/bin-prettier.js:14613:18)
[error]     at /artemis-frontend/frontend/node_modules/prettier/bin-prettier.js:14563:47
[error]     at Object.printComments (/artemis-frontend/frontend/node_modules/prettier/bin-prettier.js:14236:19)
[error]     at printGenerically (/artemis-frontend/frontend/node_modules/prettier/bin-prettier.js:14563:22)
[error]     at FastPath.call (/artemis-frontend/frontend/node_modules/prettier/bin-prettier.js:14356:20)
[error]     at printNode (/artemis-frontend/frontend/node_modules/@prettier/plugin-php/src/printer.js:2310:34)
[error]     at Object.genericPrint [as print] (/artemis-frontend/frontend/node_modules/@prettier/plugin-php/src/printer.js:93:32)
[error]     at callPluginPrintFunction (/artemis-frontend/frontend/node_modules/prettier/bin-prettier.js:14613:18)
```

I think though I'm not fully sure but it might be because of this changeset in Prettier itself: https://github.com/prettier/prettier/pull/7791.

The issue comes from where my code is type casting to a variable like `(object) $someObject`.

**Comment by czosel** [comment]
Hi @duclet, thanks for the big report! Can you post a code snippet that shows the error? I wasn’t able to reproduce it with a very simple type cast: [see playground](YzAAHUwtgBIpdHQAAgBeQ4AKdA4AKygYmABKQ52ONggAbhB2oA)

**Comment by duclet** [comment]
I'm closing this issue. Turns out there were some weird caching going on with my docker image that is the cause of this.
