### ISSUE TITLE
TypeError: locEnd is not a function

### ISSUE THREAD

**Issue by halmos** [prettier/plugin-php#1492]
Following up on issue #1352, I'm getting the same error using plugin-php version 0.14.2 and prettier version 2.0.1 with VS-code prettier plugin 5.1.3.

this is the debug output: 

```
["ERROR" - 12:19:13 PM] Error formatting document.
["ERROR" - 12:19:13 PM] locEnd is not a function
TypeError: locEnd is not a function
	at isNextLineEmpty ([path to project]/artxt/node_modules/prettier/index.js:12186:42)
	at [path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1280:7
	at FastPath.map ([path to project]/artxt/node_modules/prettier/index.js:14377:21)
	at printLines ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1263:8)
	at printBlock ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1408:25)
	at printStatement ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1433:12)
	at printNode ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:2295:12)
	at Object.genericPrint [as print] ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:72:19)
	at callPluginPrintFunction ([path to project]/artxt/node_modules/prettier/index.js:14568:18)
	at [path to project]/artxt/node_modules/prettier/index.js:14518:47
	at Object.printComments ([path to project]/artxt/node_modules/prettier/index.js:14191:19)
	at printGenerically ([path to project]/artxt/node_modules/prettier/index.js:14518:22)
	at [path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1266:25
	at FastPath.map ([path to project]/artxt/node_modules/prettier/index.js:14377:21)
	at printLines ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1263:8)
	at printBlock ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1402:13)
	at printStatement ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:1433:12)
	at printNode ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:2295:12)
	at Object.genericPrint [as print] ([path to project]/artxt/node_modules/@prettier/plugin-php/src/printer.js:72:19)
	at callPluginPrintFunction ([path to project]/artxt/node_modules/prettier/index.js:14568:18)
	at [path to project]/artxt/node_modules/prettier/index.js:14518:47
	at Object.printComments ([path to project]/artxt/node_modules/prettier/index.js:14191:19)
	at printGenerically ([path to project]/artxt/node_modules/prettier/index.js:14518:22)
	at printAstToDoc ([path to project]/artxt/node_modules/prettier/index.js:14528:13)
	at coreFormat ([path to project]/artxt/node_modules/prettier/index.js:14797:15)
	at format ([path to project]/artxt/node_modules/prettier/index.js:15018:75)
	at formatWithCursor ([path to project]/artxt/node_modules/prettier/index.js:15034:12)
	at [path to project]/artxt/node_modules/prettier/index.js:50641:12
	at Object.format ([path to project]/artxt/node_modules/prettier/index.js:50661:12)
	at t.default.<anonymous> (/Users/e/.vscode/extensions/esbenp.prettier-vscode-5.1.3/dist/extension.js:1:58387)
	at Generator.next (<anonymous>)
	at s (/Users/e/.vscode/extensions/esbenp.prettier-vscode-5.1.3/dist/extension.js:1:53305)
```

Any ideas of why I'm getting this in 0.14.2?
Only slightly unusual thing about my setup is that my node_modules and package.json are in a subdirectory of the vs-code project directory, but I don't see how that would produce any issues given the output. 

Thanks for any ideas on this!

**Comment by czosel** [comment]
This issue should only occur with prettier >= 2 and plugin-php < 0.14.0. Do you also have global installations of `prettier` oder `@prettier/plugin-php`? Maybe prettier-vscode isn't picking up the local installations and falls back to a global version?

**Comment by halmos** [comment]
It's very strange. I don't have global install of prettier or plugin-php and in the backtrace posted above you can see it accessing the local node_modules. I've also confirmed that the local `node_modules` installed versions are in fact the correct versions. 

I have the Prettier Vs-code plugin setting for the Prettier path set to my node_modules and I can confirm that if it is not set correctly, php is not available as a formatting option for prettier. I think that is a solid indicator that the plugin is using the local  `./node_modules/prettier` module and finding the local plugin-php.

**Comment by czosel** [comment]
Right (sorry, I didn’t read the stack trace earlier). Can you reproduce the issue on the command line as well?

**Comment by halmos** [comment]
huh - that's interesting. the command line works without error. I guess that means there's some problem/interaction with my vs-code extension... ?

**Comment by czosel** [comment]
Yep, seems like it. Did you already try reinstalling it? Maybe it’s using a version of prettier that is shipped with the extension?

**Comment by halmos** [comment]
Thank you for your help. After further testing it does seem that the VS Code Prettier extension has some issue with having the node_modules in a subdirectory of the project folder. After installing node_modules for `prettier` and `@prettier/plugin-php` at the project root, everything seems to work ok. I'll investigate further and possibly create an issue on the extension's github page. 

thanks again!

**Comment by czosel** [comment]
Alright, good to know! Glad I could help :upside_down_face:
