### ISSUE TITLE
TypeError: memoize is not a function

### ISSUE THREAD

**Issue by 354651432** [prettier/plugin-php#1596]
**prettier@2.2.0**

**@prettier/plugin-php@0.16.0**

```sh
prettier server.php
```
**Expected behavior:**
```
/usr/lib/node_modules/@prettier/plugin-php/src/pragma.js:8
const getPageLevelDocBlock = memoize((text) => {
                             ^

TypeError: memoize is not a function
    at Object.<anonymous> (/usr/lib/node_modules/@prettier/plugin-php/src/pragma.js:8:30)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/usr/lib/node_modules/@prettier/plugin-php/src/index.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

```

**Comment by 354651432** [comment]
fixed it by `npm install -g mem `,
perhaps should add dependency 'mem' to `package.json`

**Comment by czosel** [comment]
How did you install prettier and the PHP plugin? `mem` is already a dependency of `@prettier/plugin-php`.

**Comment by 354651432** [comment]
> How did you install prettier and the PHP plugin? `mem` is already a dependency of `@prettier/plugin-php`.

`npm install -g prettier @prettier/plugin-php`
