### ISSUE TITLE
Parser errors when running prettier with `--debug-check`

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#279]
I've been testing our plugin on the symfony codebase. The output looks fine when I don't include `--debug-check`, but when I do I get many errors like this one:
```
[error] ../symfony/src/Symfony/Component/BrowserKit/Client.php: SyntaxError: Parse Error : syntax error, unexpected '}', expecting ';' on line 222
[error]     at parser.raiseError (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser.js:290:17)
[error]     at parser.error (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser.js:335:15)
[error]     at parser.expectEndOfStatement (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser.js:360:10)
[error]     at parser.read_statement (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/statement.js:387:14)
[error]     at parser.read_inner_statement (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/statement.js:186:21)
[error]     at parser.read_inner_statements (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/statement.js:86:30)
[error]     at parser.read_code_block (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/statement.js:401:14)
[error]     at parser.read_statement (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/statement.js:196:21)
[error]     at parser.read_if (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/if.js:42:19)
[error]     at parser.read_statement (/home/christian/dev/plugin-php/node_modules/php-parser/src/parser/statement.js:199:21)
```

Source code:
```php
<?php
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Symfony\Component\BrowserKit;
/**
 * @author Fabien Potencier <fabien@symfony.com>
 */
class Response
{
    protected $content;
    protected $status;
    protected $headers;
    /**
     * The headers array is a set of key/value pairs. If a header is present multiple times
     * then the value is an array of all the values.
     *
     * @param string $content The content of the response
     * @param int    $status  The response status code
     * @param array  $headers An array of headers
     */
    public function __construct(string $content = '', int $status = 200, array $headers = array())
    {
        $this->content = $content;
        $this->status = $status;
        $this->headers = $headers;
    }
    /**
     * Converts the response object to string containing all headers and the response content.
     *
     * @return string The response with headers and content
     */
    public function __toString()
    {
        $headers = '';
        foreach ($this->headers as $name => $value) {
            if (is_string($value)) {
                $headers .= $this->buildHeader($name, $value);
            } else {
                foreach ($value as $headerValue) {
                    $headers .= $this->buildHeader($name, $headerValue);
                }
            }
        }
        return $headers."\n".$this->content;
    }
    /**
     * Returns the build header line.
     *
     * @param string $name  The header name
     * @param string $value The header value
     *
     * @return string The built header line
     */
    protected function buildHeader($name, $value)
    {
        return sprintf("%s: %s\n", $name, $value);
    }
    /**
     * Gets the response content.
     *
     * @return string The response content
     */
    public function getContent()
    {
        return $this->content;
    }
    /**
     * Gets the response status code.
     *
     * @return int The response status code
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * Gets the response headers.
     *
     * @return array The response headers
     */
    public function getHeaders()
    {
        return $this->headers;
    }
    /**
     * Gets a response header.
     *
     * @param string $header The header name
     * @param bool   $first  Whether to return the first value or all header values
     *
     * @return string|array The first header value if $first is true, an array of values otherwise
     */
    public function getHeader($header, $first = true)
    {
        $normalizedHeader = str_replace('-', '_', strtolower($header));
        foreach ($this->headers as $key => $value) {
            if (str_replace('-', '_', strtolower($key)) === $normalizedHeader) {
                if ($first) {
                    return is_array($value) ? (count($value) ? $value[0] : '') : $value;
                }
                return is_array($value) ? $value : array($value);
            }
        }
        return $first ? null : array();
    }
}
```
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/BrowserKit/Response.php

**Comment by czosel** [comment]
@mgrip Do you have an idea what could cause this?

**Comment by mgrip** [comment]
Hrm just from your description it sounds like it might be failing when trying to parse the 2nd time around (ie re-parsing the result printed by the plugin, for `--debug-check`). I can try myself as well

**Comment by czosel** [comment]
Yes, i had the same thought earlier - I'll try to confirm.

**Comment by mgrip** [comment]
What's weird though is even the re-printed file is <222 lines long...

**Comment by mgrip** [comment]
Oh wait I think this is a different file than the one with the error symfony/src/Symfony/Component/BrowserKit/Client.php

**Comment by czosel** [comment]
Actually i can't reproduce it anymore on the latest master with the file mentioned above, so it might have been a comment-related error that only came up in the already-formatted file?

**Comment by mgrip** [comment]
Ah ya it was similar to https://github.com/prettier/plugin-php/issues/273, which would have caused an error when parsing the 2nd time

**Comment by czosel** [comment]
Right - I'll take a close look at the doubly-parsed version next time I see this. Thanks!

PS: The number of successful tests on the symfony is quite impressive now, I'm hopeful :smile:  :tada:

**Comment by mgrip** [comment]
🎉 we're getting close!
