### ISSUE TITLE
Parse Error : syntax error, unexpected '::' (T_DOUBLE_COLON), expecting ';'

### ISSUE THREAD

**Issue by dragoscirjan** [prettier/plugin-php#596]
Hey there!

Pretty good work. Totally amased by the prettier project!

Please see the following code sample and error. 

```php

class Countries extends RestController
{
    protected $modelClass = \App\Country::class;
    
    /**
     * Undocumented function
     *
     * @param string $key
     * @return Response
     */
    public function search($key) {
        // test auth
        if ($this->requiredAuth()) {
            return $this->respondWithUnauthenticated();
        }
        
        try {
            $data = ($this->modelClass)::where('name', 'like', strtoupper("%${key}%"))->get();
            return $this->respond($data);
        } catch (\Exception $e) {
            // TODO: Add logger ?
        }
        return $this->respondWithError('Failed retreiving data.');
    }
```

```
app\Http\Controllers\Countries.php
[error] app\Http\Controllers\Countries.php: SyntaxError: Parse Error : syntax error, unexpected '::' (T_DOUBLE_COLON), expecting ';' on line 25
[error]     at parser.raiseError (api\php\node_modules\php-parser\src\parser.js:290:17)
[error]     at parser.error (api\php\node_modules\php-parser\src\parser.js:335:15)
[error]     at parser.expectEndOfStatement (api\php\node_modules\php-parser\src\parser.js:360:10)
[error]     at parser.read_statement (api\php\node_modules\php-parser\src\parser\statement.js:383:14)
[error]     at parser.read_inner_statement (api\php\node_modules\php-parser\src\parser\statement.js:186:21)
[error]     at parser.read_inner_statements (api\php\node_modules\php-parser\src\parser\statement.js:86:30)
[error]     at parser.read_code_block (api\php\node_modules\php-parser\src\parser\statement.js:397:14)
[error]     at parser.read_statement (api\php\node_modules\php-parser\src\parser\statement.js:196:21)
[error]     at parser.read_try (api\php\node_modules\php-parser\src\parser\try.js:23:30)
[error]     at parser.read_statement (api\php\node_modules\php-parser\src\parser\statement.js:343:21)
app\Http\Controllers\RestController.php
[error] app\Http\Controllers\RestController.php: SyntaxError: Parse Error : syntax error, unexpected '::' (T_DOUBLE_COLON), expecting ';' on line 40
[error]     at parser.raiseError (api\php\node_modules\php-parser\src\parser.js:290:17)
[error]     at parser.error (api\php\node_modules\php-parser\src\parser.js:335:15)
[error]     at parser.expectEndOfStatement (api\php\node_modules\php-parser\src\parser.js:360:10)
[error]     at parser.read_statement (api\php\node_modules\php-parser\src\parser\statement.js:383:14)
[error]     at parser.read_inner_statement (api\php\node_modules\php-parser\src\parser\statement.js:186:21)
[error]     at parser.read_inner_statements (api\php\node_modules\php-parser\src\parser\statement.js:86:30)
[error]     at parser.read_code_block (api\php\node_modules\php-parser\src\parser\statement.js:397:14)
[error]     at parser.read_statement (api\php\node_modules\php-parser\src\parser\statement.js:196:21)
[error]     at parser.read_try (api\php\node_modules\php-parser\src\parser\try.js:23:30)
[error]     at parser.read_statement (api\php\node_modules\php-parser\src\parser\statement.js:343:21)
```

**Comment by evilebottnawi** [comment]
Thanks for issue, bug in parser https://github.com/glayzzle/php-parser/issues/179, should be fixed in near future
