### ISSUE TITLE
Syntax error on braces usage for dynamic methods

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#605]
Syntax error on braces usage for dynamic methods:

### Example:
```php
$foo = 'bar';
Test::{$foo};
```

### Real life case: 
```php
Order::{camel_case($name)}()
```

#### Trace
```
[error] tests/Models/OrderTest.php: SyntaxError: Parse Error : syntax error, unexpected '{' on line 54
[error]     at parser.raiseError (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser.js:290:17)
[error]     at parser.error (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser.js:335:15)
[error]     at parser.read_static_getter (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/variable.js:91:12)
[error]     at parser.read_variable (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/variable.js:69:21)
[error]     at parser.read_expr_item (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/expr.js:333:19)
[error]     at parser.read_expr (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/expr.js:11:23)
[error]     at parser.read_argument_list (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/function.js:231:17)
[error]     at parser.read_function_argument_list (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/function.js:205:31)
[error]     at parser.recursive_variable_chain_scan (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/variable.js:112:20)
[error]     at parser.read_variable (/Users/mathieutu/.config/yarn/global/node_modules/php-parser/src/parser/variable.js:72:17)

```

**Comment by evilebottnawi** [comment]
@mathieutu Thanks for issue. Bug in parser.

/cc @ichiriac
