### ISSUE TITLE
bug with static and comments

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#711]
**Prettier 1.14.3**

**PHP Plugin 0.7.0**

**Input:**

```php
// Comment
static
    // Comment
    $a // Comment
    // Comment    
    = // Comment
    // Comment
    2021;
```

**Output:**

```shell
Comment location overlaps with node location

      81 | 
      82 | function prettyprint(src, filename, options) {
    > 83 |   return prettier.format(
         |                   ^
      84 |     src,
      85 |     Object.assign(
      86 |       {

      at decorateComment (node_modules/prettier/src/main/comments.js:133:11)
      at decorateComment (node_modules/prettier/src/main/comments.js:108:7)
      at comments.forEach (node_modules/prettier/src/main/comments.js:191:5)
          at Array.forEach (<anonymous>)
      at Object.attach (node_modules/prettier/src/main/comments.js:182:12)
      at attachComments (node_modules/prettier/src/main/core.js:58:14)
      at coreFormat (node_modules/prettier/src/main/core.js:85:23)
      at format (node_modules/prettier/src/main/core.js:254:18)
      at formatWithCursor (node_modules/prettier/src/main/core.js:264:12)
      at node_modules/prettier/src/index.js:23:15
      at Object.format (node_modules/prettier/src/index.js:41:12)
      at prettyprint (tests_config/run_spec.js:83:19)
      at fs.readdirSync.forEach.filename (tests_config/run_spec.js:35:22)
          at Array.forEach (<anonymous>)
      at run_spec (tests_config/run_spec.js:22:27)
      at Object.<anonymous> (tests/comments/jsfmt.spec.js:1:28)
```

**Expected behavior:**

no errors

**Comment by czosel** [comment]
:100:
