### ISSUE TITLE
Prettier breaks on parent::{__FUNCTION__}()

### ISSUE THREAD

**Issue by thijsw** [prettier/plugin-php#858]
**Prettier 1.15.2**

**PHP Plugin 0.9.0**

In Laravel Nova the following (rather ugly) code is used:

**Input:**

```php
public static function label()
{
    return __(parent::{__FUNCTION__}());
}
```

**Output:**

```sh
app/Nova/Resource.php
[error] app/Nova/Resource.php: SyntaxError: Parse Error : syntax error, unexpected '{' on line 17
[error]     at parser.raiseError (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser.js:300:17)
[error]     at parser.error (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser.js:345:15)
[error]     at parser.read_static_getter (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/variable.js:93:12)
[error]     at parser.read_variable (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/variable.js:71:21)
[error]     at parser.read_expr_item (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/expr.js:342:19)
[error]     at parser.read_expr (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/expr.js:11:23)
[error]     at parser.read_argument_list (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/function.js:232:17)
[error]     at parser.read_function_argument_list (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/function.js:206:31)
[error]     at parser.recursive_variable_chain_scan (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/variable.js:119:20)
[error]     at parser.read_variable (/usr/local/lib/node_modules/@prettier/plugin-php/node_modules/php-parser/src/parser/variable.js:74:17)
```

**Expected behavior:**
Do nothing, just skip the line

**Comment by evilebottnawi** [comment]
Thanks for issue, bug in parser
